#!/bin/bash -e

if ! id | grep -q root; then
	echo "must be run as root"
	exit
fi

version_message="20211118.0: ReWrite from Scratch..."

broadcast () {
	if [ "x${message}" != "x" ] ; then
		echo "${message}"
		if [ "x${debug_over_display}" != "x" ] ; then
			echo "${message}" > /dev/${debug_over_display} || true
		fi
	fi
}

broadcast_file () {
	if [ -f ${bfile} ] ; then
		message="cat ${bfile}"                                       ; broadcast
		message="--------------------------------------------------" ; broadcast
		cat ${bfile}
		if [ "x${debug_over_display}" != "x" ] ; then
			cat ${bfile} > /dev/${debug_over_display} || true
		fi
	fi
}

failure () {
	message="-----------------------------" ; broadcast
}

check_running_system () {
	message="copying: [${source}] -> [${destination}]"           ; broadcast
	message="lsblk:"                                             ; broadcast
	message="`lsblk || true`"                                    ; broadcast
	message="--------------------------------------------------" ; broadcast
	message="df -h | grep rootfs:"                               ; broadcast
	message="`df -h | grep rootfs || true`"                      ; broadcast
	message="--------------------------------------------------" ; broadcast
}

###FIXME
if [ -f /etc/default/beagle-flasher ] ; then
	clear
	. /etc/default/beagle-flasher
	message="--------------------------------------------------" ; broadcast
	message="Version: [${version_message}]" ; broadcast
	message="--------------------------------------------------" ; broadcast
	bfile="/etc/default/beagle-flasher"     ; broadcast_file
	message="--------------------------------------------------" ; broadcast
else
	message="--------------------------------------------------" ; broadcast
	message="Version: [${version_message}]"                      ; broadcast
	message="--------------------------------------------------" ; broadcast
	message="ERROR: Please setup: /etc/default/beagle-flasher"   ; broadcast
	message="-----------------------------" ; broadcast
	message="Example:" ; broadcast
	message="--------------------------------------------------" ; broadcast
	message="debug_over_display=tty0"                            ; broadcast
	message="source=/dev/mmcblk0"                                ; broadcast
	message="destination=/dev/mmcblk1"                           ; broadcast
	message="--------------------------------------------------" ; broadcast
	failure
fi

check_running_system
