#!/bin/bash -e

if ! id | grep -q root; then
	echo "must be run as root"
	exit
fi

version_message="20211118.0: ReWrite from Scratch..."

broadcast () {
	if [ "x${message}" != "x" ] ; then
		echo "${message}"
		if [ "x${debug_video}" != "x" ] ; then
			echo "${message}" > /dev/${debug_video} || true
		fi
	fi
}

broadcast_file () {
	if [ -f ${bfile} ] ; then
		message="cat ${bfile}" ; broadcast
		message="-----------------------------" ; broadcast
		cat ${bfile}
		if [ "x${debug_video}" != "x" ] ; then
			cat ${bfile} > /dev/${debug_video} || true
		fi
		message="-----------------------------" ; broadcast
	fi
}

failure () {
	message="-----------------------------" ; broadcast
}

###FIXME
if [ -f /etc/default/beagle-flasher ] ; then
	clear
	. /etc/default/beagle-flasher
	message="-----------------------------" ; broadcast
	message="Version: [${version_message}]" ; broadcast
	message="-----------------------------" ; broadcast
	bfile="/etc/default/beagle-flasher"     ; broadcast_file
	message="-----------------------------" ; broadcast
else
	message="-----------------------------" ; broadcast
	message="Version: [${version_message}]" ; broadcast
	message="-----------------------------" ; broadcast
	message="ERROR: Please setup: /etc/default/beagle-flasher" ; broadcast
	message="-----------------------------" ; broadcast
	failure
fi
