#!/bin/bash -e

if ! id | grep -q root; then
	echo "must be run as root"
	exit
fi

version_message="20211118.0: ReWrite from Scratch..."

broadcast () {
	if [ "x${message}" != "x" ] ; then
		echo "${message}"
		if [ "x${debug_over_display}" != "x" ] ; then
			echo "${message}" > /dev/${debug_over_display} || true
		fi
	fi
}

example_failure () {
	message="ERROR: Please setup: /etc/default/beagle-flasher"                       ; broadcast
	message="----------------------------------------------------------------------" ; broadcast
	message="Example:"                                                               ; broadcast
	message="----------------------------------------------------------------------" ; broadcast
	message="debug_over_display=tty0"                                                ; broadcast
	message="source=/dev/mmcblk0"                                                    ; broadcast
	message="destination=/dev/mmcblk1"                                               ; broadcast
	message="----------------------------------------------------------------------" ; broadcast
}

check_running_system () {
	if [ "x${source}" != "x" ] && [ "x${destination}" != "x" ] ; then
		message="copying: [${source}] -> [${destination}]"                               ; broadcast
		message="lsblk:"                                                                 ; broadcast
		message="`lsblk || true`"                                                        ; broadcast
		message="----------------------------------------------------------------------" ; broadcast
		message="df -h | grep rootfs:"                                                   ; broadcast
		message="`df -h | grep rootfs || true`"                                          ; broadcast
		message="----------------------------------------------------------------------" ; broadcast
	else
		message="ERROR: Setup: [source] or [destination] in /etc/default/beagle-flasher" ; broadcast
		message="lsblk:"                                                                 ; broadcast
		message="`lsblk || true`"                                                        ; broadcast
		message="----------------------------------------------------------------------" ; broadcast
		message="df -h | grep rootfs:"                                                   ; broadcast
		message="`df -h | grep rootfs || true`"                                          ; broadcast
		message="----------------------------------------------------------------------" ; broadcast
		example_failure
	fi
}

###FIXME
if [ -f /etc/default/beagle-flasher ] ; then
	clear
	. /etc/default/beagle-flasher
	message="----------------------------------------------------------------------" ; broadcast
	message="Version: [${version_message}]" ; broadcast
	message="----------------------------------------------------------------------" ; broadcast
	message="cat /etc/default/beagle-flasher:"                                       ; broadcast
	message="`cat /etc/default/beagle-flasher`"                                      ; broadcast
	message="----------------------------------------------------------------------" ; broadcast
else
	message="----------------------------------------------------------------------" ; broadcast
	message="Version: [${version_message}]"                                          ; broadcast
	message="----------------------------------------------------------------------" ; broadcast
	example_failure
fi

check_running_system
